# Generated by Django 4.2.7 on 2024-01-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
