# Generated by Django 4.2.7 on 2024-01-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_subject_created_at_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
