# Generated by Django 4.2.7 on 2024-01-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_staff_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
