# Generated by Django 4.2.7 on 2024-01-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_staff_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
