# Generated by Django 4.2.7 on 2024-01-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_staff_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
