# Generated by Django 4.2.7 on 2024-01-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_staff_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_leave',
            old_name='data',
            new_name='date',
        ),
    ]
