# Generated by Django 4.2.7 on 2024-01-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_staff_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_feedback',
            name='status',
        ),
    ]
