# Generated by Django 4.2.7 on 2024-01-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_attendance_attendance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
