# Generated by Django 4.2.7 on 2024-01-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_staff_leave_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_leave',
            name='date',
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='start_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
