# Generated by Django 4.2.7 on 2024-01-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_staff_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='end_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='start_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
